myapp/myapp/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('accounts/',include('django.contrib.auth.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

myapp/polls/urls.py
from django.urls import path
from . import views2
#namespace just incase of many apps 
app_name = 'polls'
#used by the {% url %} name tag to specify the app
'''urlpatterns = [
    #ex polls
    path('',views.index,name='index'),
    #ex polls/34
    path('<int:question_id>/',views.details,name='details'),
    path('<int:question_id>/results',views.results,name='results'),
    path('<int:question_id>/vote',views.vote,name='vote')
]'''
urlpatterns = [ 
    path('', views2.IndexView.as_view(), name='index'), 
    path('<int:pk>/', views2.DetailView.as_view(), name='details'), 
    path('<int:pk>/results/', views2.ResultsView.as_view(), name='results'), 
    path('<int:question_id>/vote/', views2.vote, name='vote'), 
    ]

myapp/polls/models.py
from django.db import models
import datetime
from django.utils import timezone
# Create your models here.
# 
# (DATABASE PURSOSE)
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    #include the __str__inbuilt function for your own convinience
    def __str__(self):
        return self.question_text
    #custom method to this model
    def was_recently_published(self):
        return self.pub_date>=timezone.now()-datetime.timedelta(days=1)
class Choice(models.Model):
    #creating a relation between question and choices
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    #include the __str__inbuilt function for your own convinience
    def __str__(self):
        return self.choice_text
#we need our polls app installed in the settings.py file
#open the settings.py file and include it among installed apps

'''
summary
>Changeyourmodels(in models.py).
>Run python manage.pymakemigrations tocreatemigrationsforthosechanges
>Run python manage.pymigrate toapplythosechangestothedatabase.

'''

myapp/polls/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.template import loader
from .models import Question,Choice
from django.urls import reverse

# Create your views here.
def index(request):
    #creating reasonable views
    latest_question_list = Question.objects.order_by('-pub_date')
    template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list':latest_question_list
    }
    return HttpResponse(template.render(context,request))

#Write more view,mms
def details(request,question_id):
    question = get_object_or_404(Question, pk = question_id)  
    return render(request,'polls/detail.html',{'question':question})

def results(request,question_id):
    question = get_object_or_404(Question, pk = question_id)
    return render(request, 'polls/results.html',{'question':question})
def vote(request,question_id):
    #modify so that voting can take place
    question = get_object_or_404(Question,pk = question_id)
    try:
        selected_choice = question.choice_set.get(pk = request.POST['choice'])
    except(KeyError,Choice.DoesNotExist):
        return render(request,'polls/detail.html',{'question':question,
        'error_message':'Choice Does Not Exist'})
    else:
        selected_choice.votes += 1
        selected_choice.save()
    return HttpResponseRedirect(reverse('polls:results', args = (question_id,)))


#my own views
def available_choices(request):
    #we are going to pass via the choice_set function
    prim_key_num = Question.objects.count()
    question_list = {}
    for pky in range(1,prim_key_num+1):
        curr_question = Question.objects.get(pk=pky)
        choice = curr_question.choice_set.all()
        question_list[curr_question] = choice


    #template = loader.get_template('polls/index.html')
    context = {
        'question_list':question_list.items(),
        #'choice_list':choice_list
    }
    return render(request,'polls/index.html',context)
    

myapp/polls/templates/polls/detail.html

<!DOCTYPE html>
<h1>{{ question.question_text }}</h1>
{% if error_message %}<p><strong> {{error_message}} </strong></p>{% endif %}
<form action =  "{% url 'polls:vote' question.id %}" method = 'post'>
     {% csrf_token %}
     {% for choice in question.choice_set.all%}
     <input type = 'radio' name = 'choice' id = 'choice{{forloop.counter}}' value = '{{choice.id}}'>
     <label for = 'choice{{forloop.counter}}'>{{choice.choice_text}}</label><br>
    {% endfor %}
    <input type = 'submit' value = 'Vote'>
</form>
//
<ul>
{% for one_choice in question.choice_set.all%}
    <li> {{ one_choice }}</li>
{% endfor %}
</ul>
//

myapp/polls/templates/polls/index.html
   
 <!DOCTYPE html>  
   {% if latest_question_list %} 
<ul> {% for question in latest_question_list %} 
    <li><a href="{%url 'polls:details' question.id%}">{{ question.question_text }}</a></li> {% endfor %} 
</ul> 
    {% else %} 
        <p>No polls are available.</p> 
    {% endif %}
    {% if question_list %}
        {% for question,choice in question_list %}
        <h1> {{ question }} </h1>
        <hr>
        {% for one_choice in choice%}
        <h2> {{ one_choice }}</h2>
        {% endfor%}
        {% endfor %}
    {% endif %}
<h1>Choose here </h1>


myapp/polls/templates/polls/results.html
<!DOCTYPE html>
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote {{choice.votes|pluralize}}</li>
{% endfor %}
</ul>
<a href = {% url 'polls:details' question.id %}> Vote again ?</a>